typedef struct Fila* fila;
fila cria_fila();
int fila_vazia(fila f);
int tamanho(fila f);
int fila_cheia(fila f);
int insere(fila f, char placa[10]);
void insere_da_espera(fila f,fila esp);
int remover(fila f, char placa[10]);
int remove_ini(fila f);
void visualizar(fila f);
